services:

  backend:
    ports:
      - 80:80
    command: ["/start-reload.sh"]
    volumes:
      - ./app:/app

networks:
  traefik-public:
    external: false
  psidomaincheck-net:
    external: false
